assert_lefthook_installed = true

[[pre-commit.jobs]]
name = "deadnix"
glob = "*.nix"
run = "deadnix --fail {staged_files}"

[[pre-commit.jobs]]
name = "shellcheck"
glob = "*.sh"
run = "shellcheck {staged_files}"

[[pre-commit.jobs]]
name = "statix"
run = "statix check --format errfmt"

[[pre-commit.jobs]]
name = "taplo"
glob = "*.toml"
run = "taplo lint {staged_files}"

[[pre-commit.jobs]]
interactive = true
name = "treefmt"
run = "treefmt --config-file .config/treefmt.toml"
stage_fixed = true

[[pre-commit.jobs]]
name = "typos"
run = "typos -c .config/typos.toml {staged_files}"
